import { Check, LoaderCircle } from "lucide-react";

const nodes = ["input_classifier", "story_expander", "story_validator", "episode_planner", "episode_scripter", "emotional_arc_scorer", "retention_risk_analyzer", "cliffhanger_strength_scorer", "final_validator", "optimizer"];
const labels: Record<string, string> = { input_classifier: "Reading the premise", story_expander: "Growing the story world", story_validator: "Checking narrative logic", episode_planner: "Mapping the episodes", episode_scripter: "Writing the vertical cut", emotional_arc_scorer: "Tracking emotional movement", retention_risk_analyzer: "Testing watch-through", cliffhanger_strength_scorer: "Measuring the next-watch pull", final_validator: "Making the final pass", optimizer: "Sharpening the blueprint" };

export function AnalysisPipeline({ status }: { status: (node: string) => string | undefined }) {
	const active = nodes.find((node) => status(node) === "started");
	return <div className="max-w-2xl py-8"><p className="text-[11px] font-bold tracking-[.16em] text-blue uppercase">Live pipeline</p><h2 className="font-display mt-2 text-balance text-5xl">Your story is taking shape.</h2><p aria-live="polite" className="mt-4 text-sm leading-6 text-muted-foreground">{active ? `${labels[active]} is in progress…` : "Preparing the analysis…"}</p><div className="mt-10 space-y-1">{nodes.map((node, index) => { const state = status(node); return <div key={node} className={`flex items-center gap-4 border-b border-border px-3 py-4 ${state ? "bg-card" : "opacity-35"}`}><span className="tabular w-7 text-xs font-bold text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><span aria-hidden="true" className={`grid size-5 place-items-center rounded-full border ${state === "completed" ? "border-blue bg-blue text-white" : state === "started" ? "border-coral text-coral" : "border-border"}`}>{state === "completed" ? <Check size={12}/> : state === "started" ? <LoaderCircle size={12} className="animate-spin"/> : null}</span><span className="min-w-0 text-sm font-medium">{labels[node]}</span>{node === active && <span className="ml-auto shrink-0 text-[10px] font-bold tracking-[.12em] text-coral uppercase">In progress</span>}</div>; })}</div></div>;
}
